//
// Created by 曾祥瑞 on 2024/3/26.
//

#ifndef STUDENTSYSTEM_STATIC_USER_ACTION_H
#define STUDENTSYSTEM_STATIC_USER_ACTION_H

#define ALLOW_CREATE_STUDENT 1
#define ALLOW_SHOW_ALL_STUDENTS 2

#endif //STUDENTSYSTEM_STATIC_USER_ACTION_H
